config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'users#index'

  resources :contacts do
    get 'delete'
  end
  resources :personal_details

  resources :office_details

  resources :phones

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  belongs_to :user
  has_one :personal_detail
  has_one :office_detail

  validates :first_name , presence: true
  
  def full_name
    [first_name, last_name].join(" ")
  end
  
end

app/models/office_detail.rb
class OfficeDetail < ActiveRecord::Base

  belongs_to :contact
  has_many :phones
end

app/models/personal_detail.rb
class PersonalDetail < ActiveRecord::Base

  belongs_to :contact
  has_many :phones

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i 
  
  validates :email, :length => { :maximum => 100 },
                    :format => EMAIL_REGEX

end

app/models/phone.rb
class Phone < ActiveRecord::Base

  belongs_to :office_detail
  belongs_to :personal_detail

  serialize :cell_phone
  serialize :landline

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :authenticate_user! 

  def index
    @contacts =current_user.contacts
  end

  def show
    @contact = current_user.contacts.where(:id=>params[:id]).first
  end

  def create
    @contact = current_user.contacts.create(contact_param[:contact_details])
    @personal_detail = @contact.create_personal_detail(contact_param[:personal_detail])
    @office_detail = @contact.create_office_detail(contact_param[:office_detail])
    @personal_phone = @personal_detail.phones.create(contact_param[:personal_phone])
    @office_phone = @office_detail.phones.create(contact_param[:office_phone])
    if @contact.save
      flash[:success] = "Contacts created successfully."
    else
      flash[:notice] = "Contacts cannot be created."
    end
    redirect_to(root_path)
  end

  def delete
    @contact = current_user.contacts.find(params[:contact_id])
  end

  def destroy
    if current_user.contacts.find(params[:id]).destroy
      flash[:success] = "Contact deleted successfully"
    else
      flash[:notice] = "Contact cannot be deleted."
    end
    redirect_to root_path(:id => @contact_id)
  end

  def edit
    @contact = current_user.contacts.find(params[:id])
    @personal_detail =@contact.personal_detail
    @personal_phone = @personal_detail.phones
  end

  def update
    @contact = current_user.contacts.find(params[:id])
    @personal_detail = @contact.personal_detail
    @office_detail = @contact.office_detail
    if @contact.update_attributes(basic_param) && @personal_detail.update_attributes(contact_param[:personal_detail]) && @office_detail.update_attributes(contact_param[:office_detail]) 
      flash[:notice] = "Details updated successfully."
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private
  
    def contact_param
      params.require(:contact).permit(contact_details:[:first_name, :last_name], 
        personal_detail:[:address, :email, :website], personal_phone:[:cell_phone, :landline],
        office_detail:[:office_name,:office_address, :office_email, :office_website], office_phone:[:cell_phone, :landline])
    end

    def basic_param
      params.require(:contact).permit(:first_name, :last_name)
    end
end

app/controllers/office_details_controller.rb
class OfficeDetailsController < ApplicationController

  before_action :authenticate_user!
  
  def index
  end

  def new
  end

  def create
  end

  def edit
  end
end

app/controllers/personal_details_controller.rb
class PersonalDetailsController < ApplicationController
  
  before_action :authenticate_user!

  def index
  end

  def new
  end

  def create
  end

  def edit
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController

  before_action :authenticate_user!
  
  def index
  end

  def create
  end

  def new
  end

  def show
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
    
  def index
    @contacts = Kaminari.paginate_array(current_user.contacts).page(params[:page]).per(10)
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/office_details_helper.rb
module OfficeDetailsHelper
end

app/helpers/personal_details_helper.rb
module PersonalDetailsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/delete.js.erb
$("#modal_delete").html('<%= escape_javascript(render :partial => "shared/modal_delete", 
  :locals =>{:contact => @contact}) %>')
$("#deleteModal").modal("show");

app/views/contacts/edit.js.erb
$("#modal_edit").html('<%= escape_javascript(render :partial => "shared/modal_edit", 
  :locals =>{:contact => @contact,:personal_detail => @personal_detail}) %>')
$("#editModal").modal("show");

app/views/contacts/index.html.erb
<h1>Contacts#index</h1>
<p>Find me in app/views/contacts/index.html.erb</p>

app/views/contacts/new.html.erb
<h1>Contacts#new</h1>
<p>Find me in app/views/contacts/new.html.erb</p>

app/views/contacts/show.js.erb
<% if @contact %>
  $("#modal_show").html('<%= escape_javascript(render :partial => "shared/modal_show",
    :locals=>{:contact=> @contact}) %>')
  $("#myModal").modal("show");
<% else %>
  alert("No contact");
<%end%>

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <div class="btn btn-default">
    <%= link_to 'Click to logout', destroy_user_session_path, :method => :delete %>
  </div>
<% else %>
  <p>You are not signed in.</p>
  <div class="btn btn-default">
    <%= link_to 'Login', new_user_session_path %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/user_widget' %><br />
  <%= flash[:success]%><br />
  <%= flash[:notice]%><br />
  <%= yield %>

</body>
</html>

app/views/office_details/create.html.erb
<h1>OfficeDetails#create</h1>
<p>Find me in app/views/office_details/create.html.erb</p>

app/views/office_details/edit.html.erb
<h1>OfficeDetails#edit</h1>
<p>Find me in app/views/office_details/edit.html.erb</p>

app/views/office_details/index.html.erb
<h1>OfficeDetails#index</h1>
<p>Find me in app/views/office_details/index.html.erb</p>

app/views/office_details/new.html.erb
<h1>OfficeDetails#new</h1>
<p>Find me in app/views/office_details/new.html.erb</p>

app/views/personal_details/create.html.erb
<h1>PersonalDetails#create</h1>
<p>Find me in app/views/personal_details/create.html.erb</p>

app/views/personal_details/edit.html.erb
<h1>PersonalDetails#edit</h1>
<p>Find me in app/views/personal_details/edit.html.erb</p>

app/views/personal_details/index.html.erb
<h1>PersonalDetails#index</h1>
<p>Find me in app/views/personal_details/index.html.erb</p>

app/views/personal_details/new.html.erb
<h1>PersonalDetails#new</h1>
<p>Find me in app/views/personal_details/new.html.erb</p>

app/views/phones/create.html.erb
<h1>Phones#create</h1>
<p>Find me in app/views/phones/create.html.erb</p>

app/views/phones/edit.html.erb
<h1>Phones#edit</h1>
<p>Find me in app/views/phones/edit.html.erb</p>

app/views/phones/index.html.erb
<h1>Phones#index</h1>
<p>Find me in app/views/phones/index.html.erb</p>

app/views/phones/new.html.erb
<h1>Phones#new</h1>
<p>Find me in app/views/phones/new.html.erb</p>

app/views/phones/show.html.erb
<h1>Phones#show</h1>
<p>Find me in app/views/phones/show.html.erb</p>

app/views/shared/_modal_add_contact.html.erb
<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Contacts Details</h4>
      </div>
      <div class="modal-body">
        <%= form_for :contact, :url => contacts_path do |form| %>
          <h4 class="modal-title" id="myModalLabel">Contacts Details</h4>
          <div class="form-group">
          <%= form.fields_for :contact_details do |contact|%>
            <%= contact.text_field :first_name, :placeholder=>"First Name" %>          
            <%= contact.text_field :last_name, :placeholder=>"Last Name" %>
          <%end%>
          </div>
          <h4 class="modal-title" id="myModalLabel">Personal Details</h4>
          <%= form.fields_for :personal_detail do |personal|%>
            <div class ="form-group">
              <%= personal.text_field :address , :placeholder=>"Address"%>
              <%= personal.text_field :email, :placeholder=>"Email" %>
              <%= personal.text_field :website, :placeholder=>"Website" %>
            </div>
          <%end%>
          
          <h4 class="modal-title" id="myModalLabel">Personal Phone</h4>
          <%= form.fields_for :personal_phone do |phone|%>
            <%= phone.text_field :cell_phone , :placeholder=>"01-4298822"%>
            <%= phone.text_field :landline , :placeholder=>"9841234567"%>
          <%end%>

          <h4 class="modal-title" id="myModalLabel">Office Details</h4>
          <%= form.fields_for :office_detail do |office|%>
            <div class ="form-group">
              <%= office.text_field :office_name , :placeholder=>"Company's Name"%>
              <%= office.text_field :office_address , :placeholder=>"Address"%>
              <%= office.text_field :office_email, :placeholder=>"Email" %>
              <%= office.text_field :office_website, :placeholder=>"Website" %>
            </div>
          <%end%>

          <h4 class="modal-title" id="myModalLabel">Office Phone</h4>
          <%= form.fields_for :office_phone do |phone|%>
            <%= phone.text_field :cell_phone , :placeholder=>"01-4298822"%>
            <%= phone.text_field :landline , :placeholder=>"9841234567"%>
          <%end%>
      
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= form.submit "Submit" %>
        <%end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_delete.html.erb
<div id="deleteModal" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      Are you sure?
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
      <div type="button" class="btn btn-primary" data-dismiss="modal">
        <%= link_to "Yes" ,contact_path(contact.id), :method=>:delete ,class:"btn-primary"%>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_edit.html.erb
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Contacts Details</h4>
      </div>
      <div class="modal-body">
        <%= form_for :contact, :url => contact_path ,html:{ method: "put"} do |form| %>
            <h4 class="modal-title" id="myModalLabel">Contacts Details</h4>
            <div class="form-group">
              <%= form.text_field :first_name, :placeholder=>"First Name" %>          
              <%= form.text_field :last_name, :placeholder=>"Last Name" %>
            </div>
          <h4 class="modal-title" id="myModalLabel">Personal Details</h4>
          <%= form.fields_for :personal_detail, @contact.personal_detail do |personal|%>
            <div class ="form-group">
              <%= personal.text_field :address , :placeholder=>"Address"%>
              <%= personal.text_field :email, :placeholder=>"Email" %>
              <%= personal.text_field :website, :placeholder=>"Website" %>
            </div>
          <%end%>

          <h4 class="modal-title" id="myModalLabel">Office Details</h4>
          <%= form.fields_for :office_detail, @contact.office_detail do |office|%>
            <div class ="form-group">
              <%= office.text_field :office_name , :placeholder=>"Company's Name"%>
              <%= office.text_field :office_address , :placeholder=>"Address"%>
              <%= office.text_field :office_email, :placeholder=>"Email" %>
              <%= office.text_field :office_website, :placeholder=>"Website" %>
            </div>
          <%end%>

          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= form.submit "Update" %>
        <%end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_show.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">View Details of <%= @contact.full_name %></h4>
      </div>
      <div class="modal-body">
        <h3>Personal Details </h3>
        <ul>
          <li>Address : <%= @contact.personal_detail.address %></li>
          <li>Email : <%= @contact.personal_detail.email %></li>
          <li>Website : <%= @contact.personal_detail.website%></li>
          <li>Cell Phone : <%= @contact.personal_detail.phones.first.cell_phone %></li>
          <li>Landline : <%= @contact.personal_detail.phones.first.landline %></li>
        </ul>
        <h3>Office Details </h3>
        <ul>
          <li>Company's Name : <%= @contact.office_detail.office_name %></li>
          <li>Address : <%= @contact.office_detail.office_address %></li>
          <li>Email : <%= @contact.office_detail.office_email %></li>
          <li>Website : <%= @contact.office_detail.office_website %></li>
          <li>Cell Phone : <%= @contact.office_detail.phones.first.cell_phone %></li>
          <li>Landline : <%= @contact.office_detail.phones.first.landline %></li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<center>
  <h1>Contacts Page</h1>

<div class="btn btn-default">
  <%= link_to "Add Contacts", "",id: "add_new_contact",:remote=>true %>
</div>

<table class="table" style="width:30%; margin-top: 25px;">
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>
  <% @contacts.each do |contact|%>
  <tr>
    <td><%=contact.full_name %></td>
    <td><%= link_to "Show", contact_path(contact.id), remote: true %>
      <%= link_to "Edit" , edit_contact_path(contact.id), remote: true%>
      <%= link_to "Delete" ,contact_delete_path(contact.id) , remote: true%>
    </td>
  </tr>
  <% end %>
</table>
<%= paginate @contacts %>
</center>

<%= render 'shared/modal_add_contact' %>
<div id="modal_show">
  
</div>
<div id="modal_edit">

</div>
<div id="modal_delete">

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>